In [62]:
import pandas as pd

In [63]:
pollution = pd.read_csv("DelhiPollutionData.csv")
pollution['datetimeUtc'] = pd.to_datetime(pollution['datetimeUtc'])

In [64]:
wind = pd.read_csv("WindData.csv")
wind['valid_time'] = pd.to_datetime(wind['valid_time']).dt.tz_localize('UTC').dt.tz_convert('UTC')

In [65]:
pollution_wide = pollution.pivot_table(index = 'datetimeUtc', columns='parameter', values = 'value')
pollution_hourly = pollution_wide.resample('1h').mean()
pollution_merged = pollution_hourly.merge(wind.set_index("valid_time"), left_index = True, right_index = True, how='inner')

pollution_merged['datetime_local'] = pollution_merged.index.tz_convert('Asia/Kolkata')
pollution_merged['hour_of_day_local'] = pollution_merged['datetime_local'].dt.hour

In [66]:
modi_nrt = pd.read_csv("DL_FIRE_MODIS/fire_nrt_M-C61_799442.csv")
modi_archive = pd.read_csv("DL_FIRE_MODIS/fire_archive_M-C61_799442.csv")

In [67]:
modi_fires = pd.concat([modi_archive, modi_nrt], ignore_index=True)
modi_fires['acq_date'] = pd.to_datetime(modi_fires['acq_date'])
modi_fires = modi_fires.sort_values('acq_date')

modi_fires['acq_time_str'] = modi_fires['acq_time'].astype(str).str.zfill(4)
modi_fires['acq_datetime'] = pd.to_datetime(
    modi_fires['acq_date'].astype(str) + modi_fires['acq_time_str'],
    format='%Y-%m-%d%H%M'
).dt.tz_localize('UTC').dt.tz_convert('Asia/Kolkata')

In [68]:
wind

,valid_time,u100,v100,u10,v10,tp,latitude,longitude
0,2023-09-04 00:00:00+00:00,4.806259,-0.511749,2.127380,0.230789,0.0,28.5,77.25
1,2023-09-04 01:00:00+00:00,5.730316,-0.090347,2.628036,0.159409,0.0,28.5,77.25
2,2023-09-04 02:00:00+00:00,5.795288,-0.496841,3.289093,-0.190323,0.0,28.5,77.25
3,2023-09-04 03:00:00+00:00,4.808777,-0.928024,3.426758,-0.624496,0.0,28.5,77.25
4,2023-09-04 04:00:00+00:00,4.820664,-1.537415,3.676926,-1.155029,0.0,28.5,77.25
...,...,...,...,...,...,...,...,...
26203,2026-08-30 19:00:00+00:00,2.768860,3.647201,0.694061,1.774857,0.0,28.5,77.25
26204,2026-08-30 20:00:00+00:00,3.772995,2.917435,1.194153,1.540360,0.0,28.5,77.25
26205,2026-08-30 21:00:00+00:00,5.546585,2.150971,2.359543,1.265884,0.0,28.5,77.25
26206,2026-08-30 22:00:00+00:00,4.756134,1.675919,1.830917,1.218704,0.0,28.5,77.25
26207,2026-08-30 23:00:00+00:00,5.569153,1.342926,2.509583,1.016602,0.0,28.5,77.25

In [69]:
pollution

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6358,"Mandir Marg, New Delhi - DPCC",co,1.99,ppb,2025-02-18 20:15:00+00:00,2025-02-19T01:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
1,6358,"Mandir Marg, New Delhi - DPCC",co,1.98,ppb,2025-02-18 20:30:00+00:00,2025-02-19T02:00:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
2,6358,"Mandir Marg, New Delhi - DPCC",co,1.99,ppb,2025-02-18 21:30:00+00:00,2025-02-19T03:00:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
3,6358,"Mandir Marg, New Delhi - DPCC",co,1.99,ppb,2025-02-18 21:45:00+00:00,2025-02-19T03:15:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
4,6358,"Mandir Marg, New Delhi - DPCC",co,2.00,ppb,2025-02-18 22:00:00+00:00,2025-02-19T03:30:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,6358,"Mandir Marg, New Delhi - DPCC",wind_speed,0.30,m/s,2025-03-02 02:00:00+00:00,2025-03-02T07:30:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
11996,6358,"Mandir Marg, New Delhi - DPCC",wind_speed,0.30,m/s,2025-03-02 02:15:00+00:00,2025-03-02T07:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
11997,6358,"Mandir Marg, New Delhi - DPCC",wind_speed,0.70,m/s,2025-03-02 02:30:00+00:00,2025-03-02T08:00:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
11998,6358,"Mandir Marg, New Delhi - DPCC",wind_speed,0.80,m/s,2025-03-02 02:45:00+00:00,2025-03-02T08:15:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
11999,6358,"Mandir Marg, New Delhi - DPCC",wind_speed,0.70,m/s,2025-03-02 03:15:00+00:00,2025-03-02T08:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB